In [8]:
import numpy as np
a=np.array(list(range(10,20)))
b=np.linspace(1,7,10) #ten evenly spaced numbers between 1-7
a_square=a*a #square the arrays elementwise
print(a_square)
b_square=b*b
print(b_square)
sum_ab=b_square+a_square #add both square arrays
print(sum_ab)
print(sum([x for x in sum_ab if x%2 ==0])) #sum even elements of added array

print(sum_ab**(1/2)) #square root of added array


ab=np.append(a,b) #appending b to a
m=ab.reshape(5,4) #reshape that array
print(m) #print m
m2=m[:,1:3]
print(m2) #print m2

m3=np.transpose(m2).dot(m)
print(m3)

m3=np.around(m3,2)
print(m3) #print the new m3 which is rounded
m3dim=m3.shape
m3=np.sort(m3.ravel())[::-1].reshape(m3dim)  #flatten it and then reshape it
print(m3) #print the sorted m3

[100 121 144 169 196 225 256 289 324 361]
[  1.           2.77777778   5.44444444   9.          13.44444444
  18.77777778  25.          32.11111111  40.11111111  49.        ]
[ 101.          123.77777778  149.44444444  178.          209.44444444
  243.77777778  281.          321.11111111  364.11111111  410.        ]
588.0
[ 10.04987562  11.12554618  12.22474721  13.34166406  14.47219556
  15.61338457  16.76305461  17.91957341  19.08169571  20.24845673]
[[ 10.          11.          12.          13.        ]
 [ 14.          15.          16.          17.        ]
 [ 18.          19.           1.           1.66666667]
 [  2.33333333   3.           3.66666667   4.33333333]
 [  5.           5.66666667   6.33333333   7.        ]]
[[ 11.          12.        ]
 [ 15.          16.        ]
 [ 19.           1.        ]
 [  3.           3.66666667]
 [  5.66666667   6.33333333]]
[[ 697.33333333  748.11111111  437.88888889  482.33333333]
 [ 402.22222222  437.88888889  454.55555556  489.88888889]]
[[